name: Check

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run check
        run: check

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build
